name: centrifuge
version: 0.5.1

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Flutter and VM over dart:io WebSocket

author: German Saprykin <saprykin.h@gmail.com>
homepage: http://github.com/centrifugal/centrifuge-dart

environment:
 sdk: ">=2.12.0-0 <3.0.0"

dependencies:
 protobuf: ^2.0.0

dev_dependencies:
  test: ^1.16.6
  mockito: ^5.0.0
